version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '@types/node'
        versions: ['>24.0.0']
    groups:
      react:
        patterns:
          - 'react*'
      ui:
        patterns:
          - '@emotion*'
          - '@mui*'
      test:
        patterns:
          - '@testing-library*'
          - 'vitest'
          - '@vitest*'
          - jsdom
      types:
        patterns:
          - '@types*'
          - typescript
          - tsx
      linter:
        patterns:
          - '*biome*'
          - husky
          - prettier
      build:
        patterns:
          - '*rsbuild*'
          - '*rstest*'
